version: "3.9"
services:
  extract-media-bot:
    build: .
    container_name: extract-media-bot
    restart: always
    ports:
      - "8443:8443"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443;http://+:80
      - ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH=/https/ssl.cert.crt
      - ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__KEYPATH=/https/ssl.cert.key
    volumes:
      - /root/.aspnet/https:/https:ro